name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: |
        go mod tidy -v
        go test -v ./...
      
    - name: Coverage
    - run: |
        go test -race -coverprofile=coverage.out -covermode=atomic
